spring:
  application:
    name: platform
  datasource:
    url: jdbc:mysql://39.104.83.135:3306/smart_agri?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: kaze
    password: 901170119
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 1983517529@qq.com
    password: pmfjlrqfgxpldhfc
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
platform:
  audit:
    enable: true
    
mybatis:
  mapper-locations: classpath:mapper/planning/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    

logging:
  level:
    com.agri.platform: debug
    org.springframework.jdbc.core: debug
    root: INFO
    # Spring 启动时扫描 Mapper 接口
    org.mybatis.spring.mapper.MapperFactoryBean: TRACE
    org.mybatis.spring.SqlSessionFactoryBean: TRACE
    # MyBatis 核心内部
    org.apache.ibatis: TRACE
    org.apache.ibatis.builder: TRACE
    org.apache.ibatis.binding: TRACE
    org.apache.ibatis.session: TRACE
    org.apache.ibatis.executor: TRACE
    org.apache.ibatis.parsing: TRACE
    org.apache.ibatis.datasource: TRACE
    org.apache.ibatis.transaction: TRACE
    org.apache.ibatis.cache: TRACE
